version: '3.8'

services:
  memory-mcp:
    image: ghcr.io/tekgnosis-net/memory-mcp:latest
    ports:
      - "8099:8099"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017
      - PORT=8099
    depends_on:
      - mongodb
    networks:
      - memory-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8099', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongodb:
    image: mongo:7-jammy
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=memory_mcp
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - memory-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mongodb_data:

networks:
  memory-network:
    driver: bridge